# Generated by Django 4.0.3 on 2022-04-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptostore', '0002_client_coin_coinname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinhistory',
            name='coinCode',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='CoinHistory',
        ),
    ]
